#!/usr/bin/env bash
GPU_DEVICE="0,1,2,3,4,5,6,7"
length=${#GPU_DEVICE}
n_gpu=$(((length+1)/2))
size="7b" # [Select One] "0.5b" | "1.8b" | "3.8b" | "7b"
port=10000
dataset="mm-vet"

CUDA_VISIBLE_DEVICES=$GPU_DEVICE \
accelerate launch --config_file utils/ddp_accel.yaml \
--num_processes=$n_gpu \
--main_process_port=$port \
test.py \
--batch_size 1 \
--dataset $dataset \
--size $size \